In [1]:
# this is to silence warnings about us using pandas oddly - avoid doing this!
import warnings
warnings.filterwarnings('ignore')

In [2]:
# importing the pandas library and giving it a shorter alias
import pandas as pd

In [3]:
# loading in data

# standard loading of the data, no options
#dfRaw = pd.read_csv("cleaned-with-latlng.csv")

# specify encoding
dfRawEnc = pd.read_csv("../data/cleaned-with-latlng.csv", encoding='latin1')

# specify data type of fields
# dfTyped = pd.read_csv("cleaned-with-latlng.csv", dtype = {
#    "Latitude": float,
#    "Road Surface": str
# })

In [4]:
# printing a view of the dataframe
dfRawEnc

,Reference Number,Latitude,Longitude,Number of Vehicles,Accident Date,Time (24hr),1st Road Class,Road Surface,Lighting Conditions,Weather Conditions,Casualty Class,Casualty Severity,Sex of Casualty,Age of Casualty,Type of Vehicle
0,202609,53.891468,-1.667699,2,14-Mar-09,2330,Unclassified,Dry,Darkness: no street lighting,Fine with high winds,Driver/Rider,Slight,Male,30,Car
1,202609,53.891468,-1.667699,2,14-Mar-09,2330,Unclassified,Dry,Darkness: no street lighting,Fine with high winds,Driver/Rider,Slight,Female,20,Car
2,810209,53.933915,-1.374070,1,03-Oct-09,630,A(M),Dry,Darkness: no street lighting,Fine with high winds,Driver/Rider,Slight,Male,29,Car
3,972109,53.911349,-1.384957,4,19-Nov-09,630,A(M),Dry,Darkness: no street lighting,Fine with high winds,Driver/Rider,Slight,Male,17,Car
4,972109,53.911349,-1.384957,4,19-Nov-09,630,A(M),Dry,Darkness: no street lighting,Fine with high winds,Driver/Rider,Slight,Male,53,Goods vehicle 3.5 tonnes mgw and under
5,110060585,53.728641,-1.446131,1,07-Feb-11,128,Motorway,Dry,Darkness: no street lighting,Fine with high winds,Driver/Rider,Slight,Male,39,Goods vehicle 3.5 tonnes mgw and under
6,140007543,53.936555,-1.375203,2,07-Jan-14,240,A(M),Wet / Damp,Darkness: no street lighting,Fine with high winds,Driver/Rider,Serious,Male,60,Goods vehicle 7.5 tonnes mgw and over
7,140007543,53.936555,-1.375203,2,07-Jan-14,240,A(M),Wet / Damp,Darkness: no street lighting,Fine with high winds,Driver/Rider,Serious,Male,41,Goods vehicle 7.5 tonnes mgw and over
8,812709,53.787935,-1.469894,1,03-Oct-09,2110,Unclassified,Dry,Darkness: street lighting unknown,Fine with high winds,Driver/Rider,Slight,Male,18,Car
9,110168779,53.782784,-1.560866,2,11-Apr-11,2100,Unclassified,Dry,Darkness: street lighting unknown,Fine with high winds,Driver/Rider,Slight,Male,31,Pedal cycle
10,130159701,53.721443,-1.542501,2,17-Apr-13,2125,A,Dry,Darkness: street lighting unknown,Fine with high winds,Driver/Rider,Slight,Male,19,Car
11,130044995,53.774655,-1.582649,2,30-Jan-13,1800,A,Wet / Damp,Darkness: street lighting unknown,Fine with high winds,Driver/Rider,Slight,Female,39,Car
12,10BA0528553,53.817396,-1.516274,2,10-Dec-10,1630,A,Wet / Damp,Darkness: street lighting unknown,Fine with high winds,Driver/Rider,Slight,Female,48,Car
13,110113445,53.745342,-1.470339,3,10-Mar-11,608,Unclassified,Dry,Darkness: street lights present and lit,Fine with high winds,Driver/Rider,Serious,Male,24,Motorcycle over 125cc and up to 500cc
14,130159741,53.807748,-1.634710,3,17-Apr-13,2110,Unclassified,Dry,Darkness: street lights present and lit,Fine with high winds,Driver/Rider,Serious,Male,37,Motorcycle over 50cc and up to 125cc
15,814809,53.798204,-1.638103,2,03-Oct-09,1930,Unclassified,Dry,Darkness: street lights present and lit,Fine with high winds,Driver/Rider,Slight,Female,51,Car
16,110023466,53.801690,-1.487121,2,15-Jan-11,1938,Unclassified,Dry,Darkness: street lights present and lit,Fine with high winds,Driver/Rider,Slight,Male,35,Car
17,110113445,53.745342,-1.470339,3,10-Mar-11,608,Unclassified,Dry,Darkness: street lights present and lit,Fine with high winds,Driver/Rider,Slight,Male,60,Goods vehicle 3.5 tonnes mgw and under
18,110237263,53.851936,-1.555674,1,24-May-11,210,Unclassified,Dry,Darkness: street lights present and lit,Fine with high winds,Driver/Rider,Slight,Male,31,Car
19,120084311,53.730142,-1.510319,1,22-Feb-12,2142,Motorway,Dry,Darkness: street lights present and lit,Fine with high winds,Driver/Rider,Slight,Male,29,Goods vehicle 7.5 tonnes mgw and over
20,120084365,53.843431,-1.557451,2,23-Feb-12,1853,Unclassified,Dry,Darkness: street lights present and lit,Fine with high winds,Driver/Rider,Slight,Male,29,Car
21,130053805,53.796247,-1.469531,2,04-Feb-13,630,A,Dry,Darkness: street lights present and lit,Fine with high winds,Driver/Rider,Slight,Male,39,Pedal cycle
22,130127630,53.728199,-1.479997,2,26-Mar-13,103,Motorway,Dry,Darkness: street lights present and lit,Fine with high winds,Driver/Rider,Slight,Male,27,Car
23,10BA0006850,53.828597,-1.393887,2,11-Nov-10,1800,Unclassified,Dry,Darkness: street lights present and lit,Fine with high winds,Driver/Rider,Slight,Male,38,Car
24,1CN1299,53.792643,-1.568095,2,23-Dec-14,1915,A,Dry,Darkness: street lights present and lit,Fine with high winds,Driver/Rider,Slight,Male,28,Car
25,10CA0521587,53.746725,-1.639364,1,07-Dec-10,30,A,Frost / Ice,Darkness: street lights present and lit,Fine with high winds,Driver/Rider,Slight,Male,30,Car
26,110054111,53.817420,-1.531266,5,02-Feb-11,1800,Unclassified,Wet / Damp,Darkness: street lights present and lit,Fine with high winds,Driver/Rider,Serious,Male,40,Car
27,130420213,53.806820,-1.584106,2,11-Oct-13,1910,A,Wet / Damp,Darkness: street lights present and lit,Fine with high winds,Driver/Rider,Serious,Male,52,Pedal cycle
28,193209,53.834637,-1.651845,2,03-Mar-09,1939,A,Wet / Damp,Darkness: street lights present and lit,Fine with high winds,Driver/Rider,Slight,Male,46,Pedal cycle
29,810409,53.870476,-1.647152,2,03-Oct-09,2205,Unclassified,Wet / Damp,Darkness: street lights present and lit,Fine with high winds,Driver/Rider,Slight,Male,35,Car
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18853,2CU0971,53.804984,-1.578248,1,30-Dec-15,1500,A,Wet / Damp,Daylight: street lights present,Raining without high winds,Pedestrian,Slight,Female,61,Car
18854,21S1315,53.778642,-1.528056,1,28-Jan-15,1833,Unclassified,Snow,Darkness: street lights present and lit,Snowing with high winds,Pedestrian,Slight,Male,52,Car
18855,21S1315,53.778642,-1.528056,1,28-Jan-15,1833,Unclassified,Snow,Darkness: street lights present and lit,Snowing with high winds,Pedestrian,Slight,Male,28,Car
18856,10BA0514491,53.856430,-1.563015,1,01-Dec-10,1530,Unclassified,Snow,Daylight: street lights present,Snowing with high winds,Pedestrian,Slight,Female,13,Car
18857,130063450,53.791598,-1.593258,1,25-Jan-13,2310,Unclassified,Snow,Darkness: street lighting unknown,Snowing without high winds,Pedestrian,Serious,Female,42,Car
18858,1093709,53.808850,-1.525682,2,23-Dec-09,2050,Unclassified,Frost / Ice,Darkness: street lights present and lit,Snowing without high winds,Pedestrian,Slight,Male,60,Car
18859,10CA0000303,53.769602,-1.595125,2,09-Jan-10,2358,A,Frost / Ice,Darkness: street lights present and lit,Snowing without high winds,Pedestrian,Slight,Male,24,Car
18860,10AA0539269,53.874303,-1.706467,1,18-Dec-10,145,Unclassified,Snow,Darkness: street lights present and lit,Snowing without high winds,Pedestrian,Serious,Male,21,Car
18861,130018640,53.724828,-1.560758,2,13-Jan-13,1806,Unclassified,Wet / Damp,Darkness: street lights present and lit,Snowing without high winds,Pedestrian,Slight,Female,41,Motorcycle over 50cc and up to 125cc
18862,10AA0001701,53.808084,-1.624047,1,17-Feb-10,2115,Unclassified,Wet / Damp,Darkness: street lights present and lit,Snowing without high winds,Pedestrian,Slight,Male,32,Car
18863,1059909,53.828825,-1.685484,3,18-Dec-09,1210,Unclassified,Snow,Daylight: street lights present,Snowing without high winds,Pedestrian,Serious,Female,61,Car
18864,10AA0550633,53.896389,-1.730737,1,27-Dec-10,1127,A,Snow,Daylight: street lights present,Snowing without high winds,Pedestrian,Serious,Female,56,Car
18865,94809,53.779694,-1.559017,1,04-Feb-09,800,Unclassified,Snow,Daylight: street lights present,Snowing without high winds,Pedestrian,Slight,Female,44,Car
18866,1064109,53.779787,-1.524492,2,18-Dec-09,1100,A,Snow,Daylight: street lights present,Snowing without high winds,Pedestrian,Slight,Male,18,Car
18867,110010555,53.840232,-1.515723,1,07-Jan-11,1100,Unclassified,Snow,Daylight: street lights present,Snowing without high winds,Pedestrian,Slight,Male,55,Goods vehicle 3.5 tonnes mgw and under
18868,10AA0000386,53.792355,-1.660316,1,10-Jan-10,1305,Unclassified,Snow,Daylight: street lights present,Snowing without high winds,Pedestrian,Slight,Male,26,Car
18869,21T0922,53.818744,-1.469475,1,29-Jan-15,1523,Unclassified,Snow,Daylight: street lights present,Snowing without high winds,Pedestrian,Slight,Female,38,Goods vehicle 3.5 tonnes mgw and under
18870,10AA0001604,53.828516,-1.605055,1,07-Feb-10,1,Unclassified,Dry,Darkness: street lighting unknown,Unknown,Pedestrian,Serious,Female,34,Taxi/Private hire car
18871,112209,53.817496,-1.599478,1,19-Jan-09,1730,Unclassified,Dry,Darkness: street lighting unknown,Unknown,Pedestrian,Slight,Female,27,Goods vehicle 3.5 tonnes mgw and under
18872,10CA0511888,53.791287,-1.556239,2,27-Nov-10,2300,Unclassified,Frost / Ice,Darkness: street lighting unknown,Unknown,Pedestrian,Slight,Female,16,Car
18873,1411033,53.777888,-1.526182,1,29-Mar-14,2340,Unclassified,Wet / Damp,Darkness: street lighting unknown,Unknown,Pedestrian,Serious,Male,36,Car
18874,110025643,53.800534,-1.541323,1,16-Jan-11,1715,Unclassified,Wet / Damp,Darkness: street lighting unknown,Unknown,Pedestrian,Slight,Male,20,Car
18875,1BB1391,53.902265,-1.703151,1,11-Nov-14,1740,A,Wet / Damp,Darkness: street lighting unknown,Unknown,Pedestrian,Slight,Male,10,Car
18876,130429798,53.780171,-1.530633,1,17-Oct-13,1915,Unclassified,Dry,Darkness: street lights present and lit,Unknown,Pedestrian,Slight,Female,43,Car
18877,2C80224,53.864134,-1.697491,1,08-Dec-15,740,A,Dry,Darkness: street lights present and lit,Unknown,Pedestrian,Slight,Male,13,Car
18878,113309,53.797887,-1.540183,1,04-Feb-09,1530,Unclassified,Dry,Daylight: street lights present,Unknown,Pedestrian,Slight,Female,24,Taxi/Private hire car
18879,1430210,53.803303,-1.697336,1,03-Apr-14,750,A,Wet / Damp,Daylight: street lights present,Unknown,Pedestrian,Slight,Male,11,Taxi/Private hire car
18880,1591309,53.738711,-1.547529,1,07-May-14,1730,A,Wet / Damp,Daylight: street lights present,Unknown,Pedestrian,Slight,Female,17,Motorcycle over 50cc and up to 125cc
18881,1591309,53.738711,-1.547529,1,07-May-14,1730,A,Wet / Damp,Daylight: street lights present,Unknown,Pedestrian,Slight,Male,19,Motorcycle over 50cc and up to 125cc
18882,2530358,53.892361,-1.669062,1,03-May-15,1622,Unclassified,Wet / Damp,Daylight: street lights present,Unknown,Pedestrian,Slight,Female,23,Other Vehicle

In [5]:
# printing a view of the top n rows

dfRawEnc.head(3)

,Reference Number,Latitude,Longitude,Number of Vehicles,Accident Date,Time (24hr),1st Road Class,Road Surface,Lighting Conditions,Weather Conditions,Casualty Class,Casualty Severity,Sex of Casualty,Age of Casualty,Type of Vehicle
0,202609,53.891468,-1.667699,2,14-Mar-09,2330,Unclassified,Dry,Darkness: no street lighting,Fine with high winds,Driver/Rider,Slight,Male,30,Car
1,202609,53.891468,-1.667699,2,14-Mar-09,2330,Unclassified,Dry,Darkness: no street lighting,Fine with high winds,Driver/Rider,Slight,Female,20,Car
2,810209,53.933915,-1.374070,1,03-Oct-09,630,A(M),Dry,Darkness: no street lighting,Fine with high winds,Driver/Rider,Slight,Male,29,Car

In [6]:
# taking a subset of the columns

df = dfRawEnc[['Reference Number', 'Latitude', 'Longitude', 'Age of Casualty']]
df.head(5)

  Reference Number   Latitude  Longitude  Age of Casualty
0           202609  53.891468  -1.667699               30
1           202609  53.891468  -1.667699               20
2           810209  53.933915  -1.374070               29
3           972109  53.911349  -1.384957               17
4           972109  53.911349  -1.384957               53

In [7]:
# renaming columns

df.columns = ['referenceNumber', 'latitude', 'longitude', 'age']
df.head(5)

  referenceNumber   latitude  longitude  age
0          202609  53.891468  -1.667699   30
1          202609  53.891468  -1.667699   20
2          810209  53.933915  -1.374070   29
3          972109  53.911349  -1.384957   17
4          972109  53.911349  -1.384957   53

In [8]:
# setting a whole new column to a fixed value

df['fixedColumn'] = 3
df.head(5)

  referenceNumber   latitude  longitude  age  fixedColumn
0          202609  53.891468  -1.667699   30            3
1          202609  53.891468  -1.667699   20            3
2          810209  53.933915  -1.374070   29            3
3          972109  53.911349  -1.384957   17            3
4          972109  53.911349  -1.384957   53            3

In [9]:
# combining existing columns

df['latPlusLng'] = df['latitude'] + df['longitude']
df.head(5)

  referenceNumber   latitude  longitude  age  fixedColumn  latPlusLng
0          202609  53.891468  -1.667699   30            3   52.223769
1          202609  53.891468  -1.667699   20            3   52.223769
2          810209  53.933915  -1.374070   29            3   52.559846
3          972109  53.911349  -1.384957   17            3   52.526392
4          972109  53.911349  -1.384957   53            3   52.526392

In [10]:
# writing a function to combine existing columns in a more complex way

# if the first digit of the reference number is even then return the latitude squared, otherwise the longitude squared
def complexFunction(row):
    refFirstDigit = int(str(row['referenceNumber'])[0])
    
    if refFirstDigit % 2 == 0:
        latSq = row['latitude'] * row['latitude']
        return latSq
    else:
        lngSq = row['longitude'] * row['longitude']
        return lngSq
    
df['latOrLngSq'] = df.apply(complexFunction, axis=1)
df.head(5)

,referenceNumber,latitude,longitude,age,fixedColumn,latPlusLng,latOrLngSq
0,202609,53.891468,-1.667699,30,3,52.223769,2904.290306
1,202609,53.891468,-1.667699,20,3,52.223769,2904.290306
2,810209,53.933915,-1.374070,29,3,52.559846,2908.867206
3,972109,53.911349,-1.384957,17,3,52.526392,1.918105
4,972109,53.911349,-1.384957,53,3,52.526392,1.918105

In [11]:
# filtering the rows

under30 = df[df.age < 30]
under30.head(5)

,referenceNumber,latitude,longitude,age,fixedColumn,latPlusLng,latOrLngSq
1,202609,53.891468,-1.667699,20,3,52.223769,2904.290306
2,810209,53.933915,-1.374070,29,3,52.559846,2908.867206
3,972109,53.911349,-1.384957,17,3,52.526392,1.918105
8,812709,53.787935,-1.469894,18,3,52.318041,2893.141952
10,130159701,53.721443,-1.542501,19,3,52.178942,2.379311

In [12]:
# dropping columns

noLat = df.drop(columns=['latitude'])
noLat.head(5)

  referenceNumber  longitude  age  fixedColumn  latPlusLng   latOrLngSq
0          202609  -1.667699   30            3   52.223769  2904.290306
1          202609  -1.667699   20            3   52.223769  2904.290306
2          810209  -1.374070   29            3   52.559846  2908.867206
3          972109  -1.384957   17            3   52.526392     1.918105
4          972109  -1.384957   53            3   52.526392     1.918105

In [13]:
# fetching rows by index

df.iloc[15:20]

,referenceNumber,latitude,longitude,age,fixedColumn,latPlusLng,latOrLngSq
15,814809,53.798204,-1.638103,51,3,52.160102,2894.246795
16,110023466,53.801690,-1.487121,35,3,52.314569,2.211529
17,110113445,53.745342,-1.470339,60,3,52.275003,2.161898
18,110237263,53.851936,-1.555674,31,3,52.296263,2.420121
19,120084311,53.730142,-1.510319,29,3,52.219824,2.281063

In [15]:
# saving data

outPath = "pandas-tutorial-output.csv"
df.to_csv(outPath, index=False, header=True) # will save as csv without index column but with column names as header